### ISSUE TITLE
G920 completely unresponsive and bindings don't save. 

### ISSUE THREAD

**Issue by suddenlysouth** [E66666666/GTAVManualTransmission#104] opened 2020-12-21 14:18 UTC
I have used a g920 in the past, but now it no longer responds after a reinstall and no bindings save even though the the menu says it is able to be used as an input device.

**Comment by E66666666** [comment] 2020-12-22 10:48
Check your read/write settings on the GTA V folder, or more specifically, the ManualTransmission folder.

Not a bug, closing it.

**Closed by E66666666** 2020-12-22 10:48 UTC
Labels: bug
