### ISSUE TITLE
Car does not work with automatic gearbox

### ISSUE THREAD

**Issue by Arwic** [E66666666/GTAVManualTransmission#34] opened 2018-12-23 05:40 UTC
Video of the issue: https://www.youtube.com/watch?v=tQhV0PRh5vk

The car can be put into reverse (sometimes) and will move, but when trying to drive forward it cycles through gears very quickly and only moves very slightly, if at all. Fiddling with the clutch seems to help a bit.

[Gears.log](https://github.com/E66666666/GTAVManualTransmission/files/2705758/Gears.log)
[settings_general.ini](https://github.com/E66666666/GTAVManualTransmission/files/2705759/settings_general.ini.txt)
[settings_menu.ini](https://github.com/E66666666/GTAVManualTransmission/files/2705760/settings_menu.ini.txt)
[settings_wheel.ini](https://github.com/E66666666/GTAVManualTransmission/files/2705761/settings_wheel.ini.txt)

Everything seems to work fine when using sequential gearbox.

**Comment by E66666666** [comment] 2018-12-23 16:18
Duplicate of #33. I'm aware it's broken, but I don't have time to work on this currently.

**Closed by E66666666** 2018-12-23 16:18 UTC
