### ISSUE TITLE
Reverse stalls

### ISSUE THREAD

**Issue by SaggyBlackSack** [E66666666/GTAVManualTransmission#41] opened 2019-10-09 20:42 UTC
Hiya as it says on tin, reverse stalls for the last 2 versions. Happy fixing!

🍡 No really please fix the silent gear bug. It really is that A BUG. Please just trigger a fake gear change on a indiependent level or something...? Can't you just package the mod with gear SFX that total 15 megs? It's major flaw my friend. I love your mod, I know you don't believe me because I haven't been able to record a smooth video, but your mod is... get ready for this I mean it all I possibly can... the best driving sim enabler ever. I feel this is the best driving system I've ever played in any game ever. Cheers a lot!!!

**Comment by E66666666** [comment] 2019-10-12 22:08
I haven't been able to reproduce this.  What settings does this occur under?

Note that stalling is expected behaviour if the speed is too low for the current gear, and the clutch hasn't been used.

**Comment by SaggyBlackSack** [comment] 2019-10-13 01:27
https://pastebin.com/cVtrUnpC

You are aware sitting in reverse does not require the clutch to be touched at all, in real life? Reverse disengages the flywheel and uses a seperate drive chain to switch into a different clutch, going to opposite way. Cars in real life, even from 1970 can sit in reverse, accidentally most of the times, and you can get out and leave the car in reverse and it still won't roll back unless you just reved it with the clutch down and let go of that peddal before the accelerator.

Apart from this issue, could you please make it possible to get out my car and leave it clutch creeping? That's so we can roll cars off cliffs and embankments. Gotta gid rid of them bodys, ya know.

**Comment by SaggyBlackSack** [comment] 2019-10-13 01:28
I mean, haven't you seen dash cam videos of cars sitting with their reverse lights on, scaring people but the person isn't actually in the car. I see them from russia a lot

**Comment by E66666666** [comment] 2019-10-13 16:02
> You are aware sitting in reverse does not require the clutch to be touched at all, in real life? Reverse disengages the flywheel and uses a seperate drive chain to switch into a different clutch, going da opposite way.

What. (Manual transmission) cars just stall when the clutch is engaged while in any gear at a too low speed, same applies to reverse. Automatics shouldn't stall at all since there's that weird liquid torque converter thing.

You're in [Sequential manual transmission](https://en.wikipedia.org/wiki/Sequential_manual_transmission) mode, with the corresponding stalling option enabled. Of course it stalls.

>could you please make it possible to get out my car and leave it clutch creeping?

Due to how the script only manages one vehicle at a time, not feasible.

**Comment by SaggyBlackSack** [comment] 2019-10-13 16:27
You are wrong. I am not pressing the clutch. Putting any car into reverse gear stalls it when stopped, unless holding the clutch.

Do you understand? Reverse stalls. Reverse stalls, it shouldn't

**Comment by SaggyBlackSack** [comment] 2019-10-13 16:29
Liquid torque? why are you just messing around? I just want the SFX to work for shifts to and from first, and for reverse to not stall when holding the brake. I can't make real life any clearer, REVERSE does not stall a car even if the "revs are low". You don't need to even be IN the car to make it stay in reverse, you can just shift to reverse and sit there.

**Comment by E66666666** [comment] 2019-10-14 13:16
> 
> 
> You are wrong. I am not pressing the clutch. Putting any car into reverse gear stalls it when stopped, unless holding the clutch.
> 
> Do you understand? Reverse stalls. Reverse stalls, it shouldn't

When *not* pressing the clutch while being in *any* gear, including reverse, with a speed too low for the RPM range - the car stalls, as it should.


> 
> 
> Liquid torque? why are you just messing around? I just want the SFX to work for shifts to and from first, and for reverse to not stall when holding the brake. I can't make real life any clearer, REVERSE does not stall a car even if the "revs are low". You don't need to even be IN the car to make it stay in reverse, you can just shift to reverse and sit there.

[Torque converters](https://www.youtube.com/watch?v=PI2RPGcKdPA).

For conventional manual gearboxes - reverse is just a gear like any other gear, the gearbox layout just connects it so the drive is reversed. Reverse stalls the car. [If you don't know how to drive yet, here's an example of reversing a car.](https://www.youtube.com/watch?v=ikbzDyySK30)

I'm closing this issue, as this is not a problem and everything is working as intended.

**Closed by E66666666** 2019-10-14 13:16 UTC
Labels: question, wontfix

**Comment by SaggyBlackSack** [comment] 2019-10-14 14:16
That video is about reversing. I'm talking about sitting still whilst in reverse does not requrie the clutch in real life. Are you saying it does? I will ask my mum don't make me mf

**Comment by E66666666** [comment] 2019-10-14 14:28
For future questions, ensure you know how to operate a vehicle before reporting expected behaviour as an issue.

**Comment by SaggyBlackSack** [comment] 2019-10-15 01:42
Do you have Aspergers? 

The fact you find this a robotic factual error rather than just funny is concerning...
